# Uncomment this line to define a global platform for your project
# platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end

  # Fix for PhaseScriptExecution failed with a nonzero exit code (readlink issue)
  # This patches the CocoaPods script to use 'readlink -f' which handles paths with spaces correctly
  puts "Applying readlink -f fix for Xcode 14.3+"
  Dir.glob(File.join("Pods", "Target Support Files", "**", "*-frameworks.sh")).each do |file|
    text = File.read(file)
    if text.include?('readlink "${source}"') || text.include?('readlink "${binary}"')
      puts "Patching #{file}..."
      new_contents = text.gsub('source="$(readlink "${source}")"', 'source="$(readlink -f "${source}")"')
      new_contents = new_contents.gsub('binary="${dirname}/$(readlink "${binary}")"', 'binary="${dirname}/$(readlink -f "${binary}")"')
      File.open(file, "w") {|f| f.puts new_contents }
    end
  end
end
